# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install OpenCV dependencies
      run: |
          choco install opencv --version 4.5.1 --params "'/IncludeDir:C:\tools\opencv\build\include /LibDir:C:\tools\opencv\build\x64\vc14\lib'"

    - name: Verify OpenCV header file
      run: |
          if exist "C:\tools\opencv\build\include\opencv2\opencv.hpp" (
            echo "OpenCV header file found"
          ) else (
            echo "OpenCV header file not found"
            exit 1
          )
